spring:
  application:
    name: skyand_ai_lms_user
  datasource:
    url: jdbc:mariadb://192.168.45.201:3306/skyand_ai_lms?characterEncoding=UTF-8&serverTimezone=UTC
    username: skyand
    password: "!skyand2022"
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: 192.168.45.200
      port: 6379
      password: "!skyand2022"
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB  
  mail:
    host: smtp.mailplug.co.kr
    port: 465
    username: sed0304@skyand.co.kr
    password: /* password */
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.mailplug.co.kr
          starttls:
            enable: true
        debug: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

file:
  upload-dir: /uploads

ssh:
  # host: 13.125.101.212
  host: 52.69.3.104
  port: 22
  username: ec2-user
  pem-path: /uploads/skyand_ai_key_tokyo.pem
  key-passphrase: "!skyand2024"
  remote-dir: /home/ec2-user/python-sinhan

ai:
  server:
    # url: http://13.125.101.212:8200
    url: http://52.69.3.104:8200
    
server:
  port: 18082
